on:
  push:
    branches: 
      - master
name: Master Build/Deploy
env:
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
  GCLOUD_EMAIL: ${{ secrets.GCLOUD_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: goodbot
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '13'
    - name: Update permissions on mvnw
      run: chmod 700 mvnw
    - name: Package
      run: ./mvnw clean verify -P git-commit,integration --no-transfer-progress
